[dosbox]
machine = svga_s3
memsize = 16

[sdl]
fullscreen = false
output = texture

[cpu]
core = normal

[webserver]
mount_allowed_bases = /work
mount_allowed_image_roots = /work

[autoexec]
mount c /work
c:
