FROM localhost/ntvdm:latest

COPY ["third_party/dos_compilers/Borland Turbo Pascal v7", "/opt/dosroot/TP"]
COPY containers/dwed/build-dwed /usr/local/bin/build-dwed

RUN sed -i 's#D:\\TP\\UNITS#C:\\TP\\UNITS#' /opt/dosroot/TP/BIN/TPC.CFG && \
    ln -s /work /opt/dosroot/WORK && \
    chmod +x /usr/local/bin/build-dwed

ENTRYPOINT ["build-dwed"]
