FROM alpine:3.21

RUN apk add --no-cache bash mtools

COPY create-image /usr/local/bin/create-image
RUN sed -i 's/\r$//' /usr/local/bin/create-image && chmod +x /usr/local/bin/create-image

WORKDIR /work
ENTRYPOINT ["create-image"]
